### ISSUE TITLE
consul not logging on Upstart

### ISSUE THREAD

**Issue by jeremyjh** [savagegus/ansible-consul#182]
consul is not logging when using upstart - at least on Ubuntu. `/var/log/consul` will remain empty.

This is due to a bug introduced in df103490f46f92c6434a42e6f37e3cdd42441bcd . 

This line is incorrect because `&>>` is bash syntax, it is not compatible with `bin/sh`.

```shell
  exec su -s /bin/sh -c 'GOMAXPROCS=`nproc` exec "$0" "$@" &>>{{ consul_log_file }}' consul -- /opt/consul/bin/consul agent 
```

This should resolve the issue:

```shell
  exec su -s /bin/sh -c 'GOMAXPROCS=`nproc` exec "$0" "$@" 1>> {{ consul_log_file }} &2>1' consul -- /opt/consul/bin/consul agent 
```

**Comment by jzvelc** [comment]
You got closer but an issue with permissions remains (you can't write logs in /var/log as a consul user).
What about something like this?
```
 exec su -s /bin/sh -c 'GOMAXPROCS=`nproc` exec "$0" "$@"' consul -- /opt/consul/bin/consul agent > {{ consul_log_file }} 2>&1
```
I have tested this out and it works as expected on debian/ubuntu (with upstart) but I am not sure about rhel/centos.

**Comment by jeremyjh** [comment]
You can.../var/log/consul is touched and chown to consul:consul during
install I believe - that is the owner after install in any case.
The previous code worked the same way in this regard and I've used my
branch for successful deployments already on Ubuntu.

**Comment by jzvelc** [comment]
I just checked and I can confirm owner/g is consul:consul so it seems it is something else... Can you check if stopping/restarting upstart service works as expected? If I try to restart it I get `stop: Unknown instance:`. So the issue is that service doesn't stop and restarting fails due to address already in use error.
Please check following log file: /var/log/upstart/consul.log
With your script I get following entries:
`/opt/consul/bin/consul: 1: /opt/consul/bin/consul: cannot create 1: Permission denied`

**Comment by jzvelc** [comment]
What about this:
`exec su -s /bin/sh -c 'GOMAXPROCS=`nproc` exec "$0" "$@" > /var/log/consul 2>&1' consul -- /opt/consul/bin/consul agent`

This also works for me.

**Comment by jeremyjh** [comment]
The only difference is it would totally wipe out the log each restart since
you are not appending. We could touch and chown the log before we su to be
sure in case permissions are a problem in some context.

Restarts are a different issue but I don't think it worked under sudo
either.
